import type { Metadata } from 'next';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Basic Practice of webGL',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>WebGPU practice</title>
        <meta
          name="description"
          content="The WebGPU Samples are a set of samples demonstrating the use of the WebGPU API."
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
      </head>
      <body className={inter.className}>
        <section>
          <nav className="main-nav">
            <h1>
              <Link href="/">WGPU practice</Link>
            </h1>
            <ul>
              <h2>2D</h2>
              <li>Circle</li>
              <li>Triangle</li>
            </ul>
            <ul>
              <h2>3D</h2>
              <li>Circle</li>
              <li>Triangle</li>
            </ul>
          </nav>
        </section>
        {children}
        <footer className="footer">
          <div> Copyright by Victoria Kim</div>
          {/*
           <div>
            <a href={`https://github.com/${process.env.REPOSITORY_NAME}`}>
              Github
            </a>
          </div>
          */}
        </footer>
      </body>
    </html>
  );
}
